- name: Install Terminal
  become: true
  pacman:
    name: '{{ item }}'
    state: present
  loop:
    - rxvt-unicode
    - bash-completion

- name: Install Appearance tools
  become: true
  pacman:
    name: '{{ item }}'
    state: present
  loop:
    - picom 
    - nitrogen
    - feh
