- name: Install required packages
  become: true
  pacman:
    name: '{{ item }}'
    state: present
  loop:
    - git
    - curl
    - zlib
    - bzip2
    - readline
    - sqlite
    - openssl
    - libffi
    - base-devel

- name: Install Pyenv
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ pyenv_install_dir }}"
    version: master
    update: yes
    clone: yes

- name: Install Pyenv-virtualenv plugin
  git:
    repo: 'https://github.com/pyenv/pyenv-virtualenv.git'
    dest: "{{ pyenv_install_dir }}/plugins/pyenv-virtualenv"
    version: master
    clone: yes

- name: Set Pyenv environment variables
  lineinfile:
    path: "{{ item }}"
    line: "{{ line }}"
  with_items:
    - "~/.bashrc"
  vars:
    line: |
      export PYENV_ROOT="{{ pyenv_install_dir }}"
      export PATH="${PYENV_ROOT}/bin:${PATH}"
      eval "$(pyenv init --path)"
      eval "$(pyenv virtualenv-init -)"

- name: Install Python version
  shell: "{{ pyenv_install_dir }}/bin/pyenv install {{ pyenv_version }}"

